version: 2
jobs:
  lint:
    working_directory: ~/manGoweb/mango-cli
    docker:
      - image: hadolint/hadolint:v1.17.0-debian
    steps:
      - checkout
      - run:
          name: hadolint
          command: hadolint docker/Dockerfile
  build:
    working_directory: ~/manGoweb/mango-cli
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
 version: 2
 test:
   jobs:
     - lint
     - build
